### ISSUE TITLE
Requesting for script to connect to loco trivia socket

### ISSUE THREAD

**Issue by shreyas24cool** [Exaphis/HackQ-Trivia#55] opened 2018-04-11 09:37 UTC
@Exaphis On sniffing my phone traffic I got that loco trivia provides questions on its websocket
& for connecting to websocket first we have to enter the socket site and in response it provides sid everytime we click the site . Then in websocket address we have to put sid value then it gets connected to socket and questions come in. 
Please weite a script so that it automatically browse the  socket address, take the sid value and with that sid and it gets connected to websocket .
If you want the sniffed traffic I can provide you

**Comment by Exaphis** [comment] 2018-04-13 14:45
Duplicate of #47

**Closed by Exaphis** 2018-04-13 14:45 UTC
