### ISSUE TITLE
HQ Trivia UK

### ISSUE THREAD

**Issue by sq1232** [Exaphis/HackQ-Trivia#63] opened 2018-04-13 16:09 UTC
Is it possible to slightly change the code to work with the UK version? I can post the sniffed traffic if that would help?

**Comment by U-r-Unknown** [comment] 2018-04-13 16:13
Ya @Exaphis asked for that. Do share the traffic

**Comment by Exaphis** [comment] 2018-04-13 16:18
Duplicate of #48

**Closed by Exaphis** 2018-04-13 16:18 UTC
